### ISSUE TITLE
[Crash]: v3.0.0 does not work on 1.18/1.18.1

### ISSUE THREAD

**Issue by ZekerZhayard** [Fuzss/nightconfigfixes#1]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.1

### Mod Version (Required)

3.0.0

### Notes (Required)

Just install the mod and launch game.
Note that the error will only be printed in the console and will not be written to latest.log.

### Crash Report (Required)

https://paste.ubuntu.com/p/NpQ5CQzXkz/

**Comment by Fuzss** [comment]
Should be fixed in v3.0.1.
