### ISSUE TITLE
[Crash] with FPS Reducer

### ISSUE THREAD

**Issue by Desymoo** [Fuzss/nightconfigfixes#3]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.4

### Notes (Required)

I realize this might not be entirely related to Night Config Fixes but I was hoping maybe you could shed some light on the conflict (I can't find a way to notify the other author). This crash only occurs when using FPS Reducer with the most recent update to NCF (v4.0.3+), it was working fine with v4.0.2 and below. I'd appreciate any insight you might have on this 🙏

### Crash Report (Required)

https://gist.github.com/Desymoo/d4b4fff445d2c3fb121047033ed3d49c

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.0.5.
