### ISSUE TITLE
[Crash]: with Artifacts

### ISSUE THREAD

**Issue by NyanMC** [Fuzss/nightconfigfixes#5]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

3.0.1

### Notes (Required)

Other mods used are:
[Artifacts](https://www.curseforge.com/minecraft/mc-mods/artifacts) 1.18.2-4.2.0
[Curios API](https://www.curseforge.com/minecraft/mc-mods/curios) 1.18.2-5.0.9.0 (dependency of Artifacts)
[ExpandAbility](https://www.curseforge.com/minecraft/mc-mods/expandability) 6.0.0 (dependency of Artifacts)

1. Proceed to Create New World screen, or attempt to open an existing world
2. Game either crashes or "datapacks" fail to load depending on which method was used

This issue does not happen without Night Config Fixes. I also tried to perform the bug without Artifacts (just its dependencies) and the issue also did not occur.

### Crash Report (Required)

https://gist.github.com/NyanMC/455858d92638a2300f3e987a6fd32c4a

**Comment by Fuzss** [comment]
Thanks for reporting, should be fixed in v3.0.2.
