### ISSUE TITLE
[Crash]: Crash after opening the Supplementaries config menu

### ISSUE THREAD

**Issue by aaronhowser1** [Fuzss/nightconfigfixes#6]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

NightConfigFixes-v4.0.6-1.19.2-Forge

### Notes (Required)

Supplementaries adds a button to the pause menu that opens its config. I got the crash below after clicking it. It's possible the crash is on their side, but the first line of the crash is
```
java.lang.ClassCastException: class fuzs.nightconfigfixes.config.ConfigSpecWrapper cannot be cast to class net.minecraftforge.common.ForgeConfigSpec (fuzs.nightconfigfixes.config.ConfigSpecWrapper is in module nightconfigfixes@4.0.6 of loader 'TRANSFORMER' @6fc1a8f6; net.minecraftforge.common.ForgeConfigSpec is in module forge@43.2.6 of loader 'TRANSFORMER' @6fc1a8f6)
```

### Crash Report (Required)

https://gist.github.com/519c2d09b57749483c7195818611ae9e

**Comment by Fuzss** [comment]
It‘s an issue with Configured, I‘ll look into it.

**Comment by Fuzss** [comment]
Same as #7.
